### ISSUE TITLE
no clear description of the project

### ISSUE THREAD

**Issue by teriiehina** [ChristopheCVB/Log#1]
This amazing project is not deserving a so poor README. A clear description is a must, no ? Something like a [README driven development](http://tom.preston-werner.com/2010/08/23/readme-driven-development.html) ;)

**Comment by ChristopheCVB** [comment]
Yep ! Working on some documentation and preparing a clear README.
Thanks for pointing this out mate ;)

**Comment by teriiehina** [comment]
That sure is great news. Please feel free to close this issue when an acceptable README will be available.
